version: '3'
services:
  db:
    image: postgres:13.1-alpine
    container_name: nutri-postgres
    environment:
      POSTGRES_USER: nutri
      POSTGRES_PASSWORD: nutri
      POSTGRES_DB: nutri
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
    ports:
    - '5432:5432'
    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh


